# -*- coding: utf-8 -*-
"""ElectiveRecommendation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j4cVL3i8WmGJyR4SDyIq3_1OUNKrSyPN
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import StandardScaler
# import matplotlib.pyplot as plt
# import seaborn as sns

df = pd.read_csv('Course_recomendation.csv')
df.head(10)


# sns.pairplot(df,hue='Recommend_Subject')
# plt.show()

X=df.iloc[:,1:-1].values
y=df.iloc[:,-1].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

classifier = DecisionTreeClassifier(random_state=42)
classifier.fit(X_train_scaled, y_train)

y_pred = classifier.predict(X_test_scaled)
results = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
# print(results)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

import pickle
with open('model.pkl', 'wb') as file:
    pickle.dump({'model': classifier, 'scaler': scaler}, file)

def function(data):
  subject={5:'Digital Electronics',4:'Material Science',3:'Sensors and Instruments',2:'Laser System and Application',1:'Energy Science and Engineering'}
  new_data=data[:3]
  new_data.append(sum(data)/len(data))
  with open('model.pkl', 'rb') as file:
      saved_model = pickle.load(file)
      loaded_classifier = saved_model['model']
      loaded_scaler = saved_model['scaler']
  return subject[loaded_classifier.predict(loaded_scaler.transform([new_data]))[0]]

print(function([85,20,89,82,30]))